### PR TITLE
Added dependency to 'openpdf', added source/target version 1.8.

### PR DESCRIPTION
**Pull request by cursor42**
Dependency was misssing.
Changed version number to 1.4.0-SNAPSHOT (using 3-digits style as in OpenPDF).

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thanks for the first contribution to this project!

**Comment by andreasrosdal** [comment]
What is the OpenPDF dependency used for? This project compiled fine without OpenPDF.

**Comment by cursor42** [comment]
Tests are using a single class from OpenPDF (com.lowagie.text.DocWriter) -> can be changed to `<scope>test</scope>`.

**Comment by andreasrosdal** [comment]
Fixed here:   https://github.com/LibrePDF/openrtf/commit/4ee476cd281ddbca77107a1c5322a57edc3bc074

Maybe we should copy that class over from OpenPDF to OpenRTF?

**Pull request merged**
